name: Send JSON Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"  # 14:00 CET

jobs:
  send_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mini-poster .

      - name: Run Docker container
        run: docker run -v $(pwd):/app mini-poster

      - name: Commit and push run history
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add run_history.json
          git diff --quiet && git diff --staged --quiet || git commit -m "ðŸ“Š Log run at $(date)"
          git push
